Main svc
voland1711/java-explore-with-me pull request #4
Opened 2023-10-20 21:03 UTC by voland1711

2023-10-23 08:27 UTC, Frilock requested changes
Добрый день, в целом все довольно хорошо, в плане комментариев в основном мелкие предложения. Еще не знаю говорил или нет, можете себе поставить плагин jpa buddy и sonarlint, покажут ряд хороших практик

2023-10-23 08:27 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/dto/compilation/UpdateCompilationRequest.java
> +    Set<Long> events;
Модификаторы приватные потеряли

2023-10-23 08:27 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/controller/AdminCategoriesController.java
> +package ru.practicum.controller;
admin контроллеры я бы вынес в отдельный подпакет все таки

2023-10-23 08:27 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/dto/event/NewEventDto.java
> +    @JsonProperty(required = true)
А зачем вы везде используете @JsonProperty(required = true)?

2023-10-23 08:27 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/model/Compilation.java
> +    String title;
Указывайте в аннотации Column размерность полей, которую задаете в скриптах создания таблиц, вроде в прошлых работах обсуждали это

2023-10-23 08:27 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/model/Compilation.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
Кажется что лучше придерживаться одного стиля работы с модификаторами, мне лично больше нравится вариант с private модификаторами у полей

2023-10-23 08:27 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/model/User.java
> +    Long id;
Модификаторы

2023-10-23 08:27 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/repository/RequestRepository.java
> +    List<Request> findAllByRequester(User user);
Вообще не знаю говорил или нет, но в IDEA можете себе поставить плагин - sonarlint, это статический анализатор кода, показывает ряд хороших практик

2023-10-23 08:27 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/service/compilations/CompilationServiceImpl.java
> +            compilation.setTitle(updateCompilationRequest.getTitle());
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2023-10-23 08:27 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/service/user/UserServiceImpl.java
> +        if (ids == null || ids.isEmpty()) {
Можно использовать CollectionUtils.isEmpty (apache common 3), а вообще конструкцию упростить, используя тернарное выражение

2023-10-23 08:27 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/service/user/UserServiceImpl.java
> +    public void deleteUserById(Long userId) {
транзакция?

2023-10-23 08:27 UTC, Frilock commented on stats/stats-server/src/main/java/ru/practicum/stats/controller/StatsController.java
>  @RequiredArgsConstructor()
Лишние скобки

2023-10-23 21:26 UTC, voland1711 commented on ewm-service/src/main/java/ru/practicum/dto/event/NewEventDto.java
> +    @JsonProperty(required = true)
Согласно спецификации это обязательные поля

2023-10-24 09:14 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/dto/event/NewEventDto.java
> +    @JsonProperty(required = true)
Так вы их проверяете через валидацию NotNull

2023-10-24 09:26 UTC, Frilock approved these changes
Добрый день, работу принимаю, все в рамках спецификации и написано хорошо. По поводу JsonProperty там у вас на некоторых полях есть валидации NotNull, по этому смысла особо не вижу ее ставить. По поводу логгирования тоже комментарий оставил

2023-10-24 09:26 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/controller/EventController.java
> +                "text = {}" +
ну все параметры конечно можно не логгировать =) Вообще идея в том, что если у вас очень большая нагрузка на сервис и идет много запросов, то нужны какие то данные в логах чтоб быстрее тот или иной запрос найти

2023-10-24 18:23 UTC, merged